### ISSUE TITLE
Actually loading file from a working directory

### ISSUE THREAD

**Issue by kaisrab** [gluc/ahp#16]
What is the file format of the loaded file? I assume .ahp but I am unable to load this file. Please help!

**Comment by gluc** [comment]
Not sure how I can help!?
Please do at least the following:
1. attach the file you are trying loading
2. describe where you stored the file
3. what is the code you used to load the file?
4. any other relevant information (e.g. OS, R version, ahp package version, etc.)

Side note: in order to try out if the syntax of your ahp file is correct, you can test your file here: https://ipub.com/dev-corner/apps/ahp/

**Comment by kaisrab** [comment]
Hello Thanks for the quick reply.

Here is the file I am trying to run. In R it is currently saying the follow
error:

> glucahp <- Load(ahpFile)
Error in value[[3L]](cond) :
  Could not load ahp model. File must be a valid YAML file. Exception
caught when parsing YAML file: Error in yaml::yaml.load(ahpString): Scanner
error: while scanning for the next token at line 48, column 1found
character that cannot start any token at line 48, column 1

Line 48 is where I start to list my pairwise comparisons. I now have the
file stores in the packages ahp folder where the other examples in your
package are stored. It was previously in my working directory.

On the AHP web example I also get the following error:
attempt to apply non-function

I have attached a screen shot of the errors and my model. Please let me
know what I am doing wrong. I am operating on OS and I use the load
function (Load) in the ahp package. Thanks your for your help.

**Comment by kaisrab** [comment]
So I have it working partially. There were a few bugs with the open spaces and I used the checker.  I am about 70% finished adding all of my alternatives. Thanks for the pointer to the online checker.
